
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.cake]

		[types.cake.createfood]
			cake_chorus_fruit = true
			cake_glow_berry = true
			berry_cream_cake_sweet_berry = true
			berry_cream_cake_chorus_fruit = true
			berry_cream_cake_glow_berry = true
			chocolate_cream_cake_butterscotch = true
			chocolate_cream_cake_caramel = true
			chocolate_cream_cake_chocolate = true
			chocolate_cream_cake_dark_chocolate = true
			chocolate_cream_cake_toffee = true
			chocolate_cream_cake_white_chocolate = true
			chorus_fruit_cream_cake_sweet_berry = true
			chorus_fruit_cream_cake_chorus_fruit = true
			chorus_fruit_cream_cake_glow_berry = true
			glow_berry_cream_cake_sweet_berry = true
			glow_berry_cream_cake_chorus_fruit = true
			glow_berry_cream_cake_glow_berry = true

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

	[types.wood_type]

		[types.wood_type.createdieselgenerators]
			chip_wood = true

		[types.wood_type.betterend]
			end_lotus = true
			jellyshroom = true
			lucernia = true
			mossy_glowshroom = true
			pythadendron = true
			dragon_tree = true
			helix_tree = true
			lacugrove = true
			tenanea = true
			umbrella_tree = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.garnished]
			sepia = true
			nut = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.vinery]
			dark_cherry = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

	[types.leaves_type]

		[types.leaves_type.environmental]
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true
			cheerful_plum = true
			moody_plum = true
			hibiscus = true
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			rainbow_birch = true
			snowblossom = true
			yellow_autumn = true
			orange_autumn = true
			maple = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.autumnity]
			yellow_maple = true
			orange_maple = true
			red_maple = true
			maple = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.betterend]
			pythadendron = true
			lacugrove = true
			dragon_tree = true
			tenanea = true
			lucernia = true

		[types.leaves_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			dining_bench = true
			drawer = true
			side_table = true
			couch = true
			table = true
			chair = true
			shelf = true
			cupboard = true
			bench = true
			pillar_trim = true
			nightstand = true

		[entries.wood_type.mcwfurnitures]
			stripped_glass_table = true
			stripped_desk = true
			end_table = true
			stool_chair = true
			stripped_lower_triple_drawer = true
			stripped_drawer_counter = true
			bookshelf_drawer = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_counter = true
			stripped_striped_chair = true
			covered_desk = true
			stripped_stool_chair = true
			stripped_modern_wardrobe = true
			cupboard_counter = true
			stripped_covered_desk = true
			coffee_table = true
			glass_table = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_double_drawer_counter = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			lower_bookshelf_drawer = true
			striped_chair = true
			stripped_large_drawer = true
			wardrobe = true
			modern_desk = true
			stripped_lower_bookshelf_drawer = true
			stripped_end_table = true
			drawer = true
			stripped_bookshelf_drawer = true
			stripped_bookshelf = true
			modern_chair = true
			chair = true
			stripped_table = true
			double_drawer_counter = true
			drawer_counter = true
			counter = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			table = true
			desk = true
			stripped_double_wardrobe = true
			stripped_double_drawer = true
			triple_drawer = true
			lower_triple_drawer = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			double_wardrobe = true
			stripped_drawer = true

		[entries.wood_type.refurbished_furniture]
			storage_cabinet = true
			storage_jar = true
			desk = true
			cutting_board = true
			drawer = true
			kitchen_sink = true
			toilet = true
			lattice_fence = true
			basin = true
			kitchen_drawer = true
			kitchen_cabinetry = true
			crate = true
			chair = true
			light_ceiling_fan = true
			table = true
			mail_box = true
			dark_ceiling_fan = true
			lattice_fence_gate = true
			bath = true
			kitchen_storage_cabinet = true

		[entries.wood_type.mcwwindows]
			louvered_shutter = true
			plank_pane_window = true
			plank_four_window = true
			stripped_log_window2 = true
			log_parapet = true
			window2 = true
			stripped_log_four_window = true
			stripped_log_window = true
			plank_window = true
			plank_window2 = true
			pane_window = true
			stripped_pane_window = true
			four_window = true
			plank_parapet = true
			blinds = true
			window = true
			shutter = true

		[entries.wood_type.redeco]
			polished_planks = true
			polished_slab = true
			display_case = true
			side_table = true
			table = true
			sword_mount = true
			polished_stairs = true
			pedestal = true
			drawer_counter = true
			cabinet = true
			stool = true
			chair = true
			counter = true
			crate = true
			coffee_table = true
			drawers = true
			cabinet_counter = true
			plank_fence = true
			plank_gate = true
			bench = true
			lattice = true
			shelf = true

		[entries.wood_type.beautify]
			blinds = true
			picture_frame = true
			trellis = true

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			vertical_slab = true
			chest = true
			hollow_log = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.create]
			window_pane = true
			window = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.refurbished_furniture]
			hedge = true

